;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        howm-find-today
        hungry-delete-backward
        keyboard-escape-quit
        ))

(setq mc/cmds-to-run-once
      '(
        View-scroll-page-forward
        browse-url-with-eww
        end-of-buffer
        helm-mini
        hungry-delete-forward
        mac-mwheel-scroll
        mouse-set-region
        org-agenda-archive-default-with-confirmation
        org-cycle-agenda-files
        read-only-mode
        tabbar-backward-tab
        ))
